export const initialState = {
    user: null,
    allUsers: null,
    allArtists: null,
    allSongs: null,
    allAlbums: null,
    filterTerm: "all",
    artistFilter: null,
    languageFilter: null,
    albumFilter: null,
    isSongPlaying: false,
    songIndex: 0,
    alertType: null,
    isSongPlaying: false,
    songIndex: 0,
};